### ISSUE TITLE
can't download vip video anymore!

### ISSUE THREAD

**Issue by irabro1992** [TAJLNsScripts/iq.com-Downloader-V2#4]
hi , i always using this script for downloading video from iq.com
but now , it only work with free video. not with vip video .
some vip video works . but i can't  download most vip video.
check the logs. thanks for ur amazing script

Single episode download selected

Story of Kunning Palace Episode 3

Failed to get extm3u from html
'program'
Downloading
12:31:25.090 INFO : N_m3u8DL-RE (Beta version) 20230628
12:31:25.099 INFO : Loading URL: ./temp.m3u8
12:31:25.099 ERROR: Object reference not set to an instance of an object.
Traceback (most recent call last):
  File "D:\My Data\iq.com-Downloader-V2-main\iq.py", line 238, in <module>
    dl_media(series_title, title)
  File "D:\My Data\iq.com-Downloader-V2-main\iq.py", line 149, in dl_media
    os.remove('./temp.m3u8')
FileNotFoundError: [WinError 2] The system cannot find the file specified: './temp.m3u8'

D:\My Data\iq.com-Downloader-V2-main>

**Comment by irabro1992** [comment]
finally , i am able to find out the problem. it solved now. thanks for your amazing script.
